//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logbook_System.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DDNA_DBEntities : DbContext
    {
        public DDNA_DBEntities()
            : base("name=DDNA_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Daily_Register> Daily_Register { get; set; }
        public virtual DbSet<Mentor_Eval> Mentor_Eval { get; set; }
        public virtual DbSet<Mentor> Mentors { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Student_Eval> Student_Eval { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<TBL_Weekly> TBL_Weekly { get; set; }
        public virtual DbSet<vw_LoginInfo> vw_LoginInfo { get; set; }
    
        public virtual ObjectResult<LoginWithUsernamePassword_Result> LoginWithUsernamePassword(string dUsername, string dPassword)
        {
            var dUsernameParameter = dUsername != null ?
                new ObjectParameter("dUsername", dUsername) :
                new ObjectParameter("dUsername", typeof(string));
    
            var dPasswordParameter = dPassword != null ?
                new ObjectParameter("dPassword", dPassword) :
                new ObjectParameter("dPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoginWithUsernamePassword_Result>("LoginWithUsernamePassword", dUsernameParameter, dPasswordParameter);
        }
    }
}
