//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Logbook_System.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Weekly
    {
        public int ID { get; set; }
        public string MentorID { get; set; }
        public string StudentID { get; set; }
        public string CellPhone { get; set; }
        public string LearnershipIntk { get; set; }
        public System.DateTime Date { get; set; }
        public string Task { get; set; }
        public string CompletedToSatisifaction { get; set; }
        public string Time { get; set; }
        public string ProblemsExperienced { get; set; }
        public string GeneralComments { get; set; }
        public string LeanerSign { get; set; }
        public string MentorSign { get; set; }
    
        public virtual Mentor Mentor { get; set; }
        public virtual Student Student { get; set; }
    }
}
